# ====================================================
# 🤖 HERRAMIENTAS ESENCIALES PARA AI AGENT (85 tools)
# ====================================================
ALLOWED_TOOLS = {
    # ============ INVOICES (12 tools) ============
    "list_invoices",
    "get_invoice",
    "create_invoice",
    "update_invoice",
    "delete_invoice",
    "email_invoice",
    "mark_invoice_sent",
    "mark_invoice_void",
    "list_invoice_payments",
    "apply_credits_to_invoice",
    "get_invoice_attachment",
    "add_invoice_attachment",
    # ============ BILLS (11 tools) ============
    "list_bills",
    "get_bill",
    "create_bill",
    "update_bill",
    "delete_bill",
    "mark_bill_void",
    "mark_bill_open",
    "list_bill_payments",
    "apply_credits_to_bill",
    "get_bill_attachment",
    "add_bill_attachment",
    # ============ CONTACTS (10 tools) ============
    "list_contacts",
    "get_contact",
    "create_contact",
    "update_contact",
    "delete_contact",
    "mark_contact_active",
    "mark_contact_inactive",
    "add_contact_address",
    "update_contact_address",
    "delete_contact_address",
    # ============ ITEMS (8 tools) ============
    "list_items",
    "get_item",
    "create_item",
    "update_item",
    "delete_item",
    "list_item_details",
    "mark_item_active",
    "mark_item_inactive",
    # ============ EXPENSES (8 tools) ============
    "list_expenses",
    "get_expense",
    "create_expense",
    "update_expense",
    "delete_expense",
    "get_expense_receipt",
    "create_expense_receipt",
    "delete_expense_receipt",
    # ============ VENDOR PAYMENTS (6 tools) ============
    "list_vendor_payments",
    "get_vendor_payment",
    "create_vendor_payment",
    "update_vendor_payment",
    "delete_vendor_payment",
    "email_vendor_payment",
    # ============ ESTIMATES (7 tools) ============
    "list_estimates",
    "get_estimate",
    "create_estimate",
    "update_estimate",
    "delete_estimate",
    "mark_estimate_accepted",
    "email_estimate",
    # ============ SALES ORDERS (7 tools) ============
    "list_sales_orders",
    "get_sales_order",
    "create_sales_order",
    "update_sales_order",
    "delete_sales_order",
    "mark_sales_order_as_void",
    "email_sales_order",
    # ============ PURCHASE ORDERS (6 tools) ============
    "list_purchase_orders",
    "get_purchase_order",
    "create_purchase_order",
    "update_purchase_order",
    "delete_purchase_order",
    "list_purchase_order_comments",
    # ============ USERS (3 tools) ============
    "list_users",
    "get_user",
    "get_current_user",
    # ============ PROJECTS (2 tools) ============
    "list_projects",
    "get_project",
}
